#!/bin/sh -
#A sample startup script for mimprint for Linux or Mac OSX.

SCALA_HOME=$HOME/net/scala/scala-current
if [ ! -d $SCALA_HOME ]; then
    HERE=`dirname $0`
    SCALA_HOME=$HERE/../../net/scala/scala-current
fi
SCALA_LIB_DIR=$SCALA_HOME/lib
[ -d $SCALA_HOME/lib ] && SCALA_LIB_DIR=$SCALA_HOME/lib
#SCALA_COMPILER_JAR=${SCALA_HOME}/lib/scala-compiler.jar
SCALA_LIBRARY_JAR=${SCALA_LIB_DIR}/scala-library.jar
#SCALA_CLASSPATH=`echo $SCALA_LIB_DIR/*.jar | tr ' ' ':'`
SCALA_CLASSPATH=${SCALA_LIBRARY_JAR}
#See also below for use of local copy of scala-library.jar

SCALAMAIN_CLASS=scala.tools.nsc.MainGenericRunner
APP_MAIN_CLASS=net.jimmc.mimprint.AppStart

machine=`uname -m`
if [ "$machine" = "Power Macintosh" ]; then
    #Running on Mac OS X
    MAC_OPT_MENUBAR="-Dapple.laf.useScreenMenuBar=true"
    MAC_OPT_DOCKNAME="-Xdock:name=mimprint"
    MAC_OPT_DOCKICON="-Xdock:icon=XXX"
    MAC_OPT_ABOUTNAME="-Dcom.apple.mrj.application.apple.menu.about.name=mimprint"
    #The useScreenMenuBar flag causes ClassCastException on startup
    MAC_OPTS="$MAC_OPT_DOCKNAME $MAC_OPT_ABOUTNAME"
    JAVA=java
else
    #Assume running on Linux.  You might want to change this location.
    if [ "$JAVAHOME" = "" ]; then
        #JAVAHOME=/u/java/j2sdk1.4.2_10
        #JAVAHOME=/u/java/jdk1.5
        JAVAHOME=/u/java/jdk1.6
    fi
fi
JAVA=${JAVA:-$JAVAHOME/bin/java}
MIMSCRIPT=$0
while [ -L $MIMSCRIPT ]; do
    MIMSCRIPT=`readlink $MIMSCRIPT`
done
MIMPRINTHOME=`dirname $MIMSCRIPT`

JAVA_ARGS="-Xmx200m"
while [ $# -gt 0 ]; do
    case "$1" in
    "-debug")
        DEBUG_PORT=2000
        JDEBUG="-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=$DEBUG_PORT,server=y,suspend=n"
        shift;
        ;;
    "-debugpause")
        DEBUG_PORT=2000
        JDEBUG="-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=$DEBUG_PORT,server=y,suspend=y"
        shift;
        ;;
    "-J")
	JAVA_ARGS="$JAVA_ARGS $2"
	shift; shift;
	;;
    *) break
	;;
    esac
done

#Use local copy of scala-library if we have it.
[ -f ${MIMPRINTHOME}/scala-library.jar ] && SCALA_CLASSPATH=${MIMPRINTHOME}/scala-library.jar
CP=${SCALA_CLASSPATH}:${MIMPRINTHOME}/mimprint.jar:${MIMPRINTHOME}/log4j.jar
LOG_CONFIG_ARGS="-Dmimprint.log4j.configfile=$MIMPRINTHOME/log4j.xml"
JAVA_ARGS="$JAVA_ARGS $LOG_CONFIG_ARGS"
exec $JAVA $JAVA_ARGS $JDEBUG $MAC_OPTS -cp $CP \
    $SCALA_MAIN_CLASS $APP_MAIN_CLASS "$@"
