#!/bin/sh -
if [ `uname -m` = "Power Macintosh" ]; then
    MAC_OPT_MENUBAR="-Dapple.laf.useScreenMenuBar=true"
    MAC_OPT_DOCKNAME="-Xdock:name=Jiv"
    MAC_OPT_DOCKICON="-Xdock:icon=XXX"
    MAC_OPT_ABOUTNAME="-Dcom.apple.mrj.application.apple.menu.about.name=Jiv"
    #The useScreenMenuBar flag causes ClassCastException on startup
    MAC_OPTS="$MAC_OPT_DOCKNAME $MAC_OPT_ABOUTNAME"
    JAVA=java
else
    JAVAHOME=/u/java/j2sdk1.4.2
    JAVA=$JAVAHOME/bin/java
fi
DEBUG_PORT=2000
MEM_OPTS="-Xmx128m"
JIVIEWERHOME=`dirname $0`
echo $JIVIEWERHOME
JDEBUG="-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=$DEBUG_PORT,server=y,suspend=n"
exec $JAVA $MEM_OPTS $JDEBUG $MAC_OPTS -jar $JIVIEWERHOME/jiviewer.jar "$@"
